/**
 * Images Defines
 */

export const IMAGES = {
  cardVisa: require('~Root/assets/images/icon-card-visa.png'),
  cardMaster: require('~Root/assets/images/icon-card-master.png'),
  cardAmerican: require('~Root/assets/images/icon-card-american.png'),
  cardPaypal: require('~Root/assets/images/icon-card-paypal.png'),
  paymentSuccess: require('~Root/assets/images/payment-success.png'),
  notFound: require('~Root/assets/images/not-found.png'),
  link: require('~Root/assets/images/link.png'),
  calendar: require('~Root/assets/images/calendar.png'),
  clock: require('~Root/assets/images/clock.png'),
  iconMovieCamera: require('~Root/assets/images/icons-movie-camera.png'),
  logo: require('~Root/assets/images/logo.png'),
  logoWhite: require('~Root/assets/images/logo_white.png'),
  iconEye16x16: require('~Root/assets/images/icon_eye16x16.png'),
  iconBack24x24: require('~Root/assets/images/icon_back24x24.png'),
  iconBackGrey24x24: require('~Root/assets/images/icon_back_grey24x24.png'),
  iconNext24x24: require('~Root/assets/images/icon_next24x24.png'),
  iconCamera24x24: require('~Root/assets/images/icon_camera24x24.png'),
  iconHome: require('~Root/assets/images/icon_home.png'),
  iconMessage: require('~Root/assets/images/icon_message.png'),
  iconCalendar: require('~Root/assets/images/icon_calendar.png'),
  iconPayment: require('~Root/assets/images/icon_payment.png'),
  iconShop: require('~Root/assets/images/icon_shop.png'),
  iconExercise: require('~Root/assets/images/icon_exercise.png'),
  iconUser: require('~Root/assets/images/icon_user.png'),
  iconBell24x24: require('~Root/assets/images/icon_bell24x24.png'),
  iconPremium: require('~Root/assets/images/icon_premium.png'),
  iconPlus: require('~Root/assets/images/icon_plus.png'),
  iconClock: require('~Root/assets/images/icon_clock.png'),
  iconSearch16x16: require('~Root/assets/images/icon_search16x16.png'),
  iconFilter24x24: require('~Root/assets/images/icon_filter24x24.png'),
  iconThreeDot: require('~Root/assets/images/icon_three_dots.png'),
  iconLogOut: require('~Root/assets/images/icon_logout24x24.png'),
  iconAbout: require('~Root/assets/images/icon_about24x24.png'),
  iconAccount: require('~Root/assets/images/icon_account24x24.png'),
  iconCustomer: require('~Root/assets/images/icon_customer24x24.png'),
  iconSettings: require('~Root/assets/images/icon_settings24x24.png'),
  chart: require('~Root/assets/images/chart.png'),
  chartSad: require('~Root/assets/images/chart_sad.png'),
  chartAfraid: require('~Root/assets/images/chart_afraid.png'),
  chartAngry: require('~Root/assets/images/chart_angry.png'),
  chartAverage: require('~Root/assets/images/chart_average.png'),
  chartCalm: require('~Root/assets/images/chart_calm.png'),
  chartHappy: require('~Root/assets/images/chart_happy.png'),
  iconWheel: require('~Root/assets/images/icon_wheel.png'),
  iconMenu: require('~Root/assets/images/icon_menu.png'),
  iconSearchWhite: require('~Root/assets/images/icon_search_white.png'),
  iconHeartWhite: require('~Root/assets/images/icon_heart_white.png'),
  iconCartWhite: require('~Root/assets/images/icon_cart_white.png'),
  iconStarYellow: require('~Root/assets/images/icon_start_yellow.png'),
};
